name: Build

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_ARCH: x86

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04 ,ubuntu-20.04, windows-2019]

    steps:
      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -yq --no-install-recommends gcc-multilib g++-multilib libssl-dev:i386

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: extension
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Checkout AMBuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: ambuild

      - name: Install AMBuild
        uses: BSFishy/pip-action@v1
        with:
          packages: ./ambuild

      - name: Build
        working-directory: extension
        shell: bash
        run: |
          unzip -qq windows/boost.zip -d windows
          unzip -qq windows/openssl.zip -d windows
          mkdir build && cd build
          perl ../curl/lib/mk-ca-bundle.pl
          python ../configure.py --enable-optimize --targets=${{env.BUILD_ARCH}} --sm-path ../sourcemod
          ambuild

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: extension/build/package

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Package
        run: |
          version=`echo $GITHUB_REF | sed "s/refs\/tags\///"`
          7z a sm-ripext-${version}-ubuntu-18.04.zip ./ubuntu-18.04/*
          7z a sm-ripext-${version}-ubuntu-20.04.zip ./ubuntu-20.04/*
          7z a sm-ripext-${version}-windows-2019.zip ./windows-2019/*
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.zip'
          tag: ${{ github.ref }}
          file_glob: true